### ISSUE TITLE
 Z170MX-Gaming 5

### ISSUE THREAD

**Issue by mpv945** [icedterminal/ga-z270x-ug#4]
How to support this motherboard?

**Comment by icedterminal** [comment]
OpenCore, and by proxy, macOS will almost certainly work for your board. Given Apple still supports hardware made in 2015. This being 100 series chipsets and 6000 series CPUs.

Furthermore, the Z170MX-G5 is an entirely different board from a completely different series. This does not relate to this repo. This repo targets a selection of Gigabytes Z270 boards.

From a technical standpoint, the 200 series chipset is connected to the CPU by a PCIe x4 link called DMI 3. Where as the 100 series is not. There are also more PCIe lanes on the 200 than the 100. This comes with many firmware changes underneath. While this shouldn't be a major issue, this means the firmware is very different between the 100 and 200 series. This can lead to many differences in OpenCore configuring and quirks that I do not know about.

I do not own a 100 series board of any kind to test. If you want to get OpenCore and macOS working on your board, you need to do that yourself. I cannot do this for you. Start with the Dortania guides. https://dortania.github.io/getting-started/
